name: dive_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"   # ← 이렇게 범위로

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.20.2
  geolocator: ^12.0.0

  permission_handler: ^11.3.0
  flutter_blue_plus: ^1.32.12
  app_settings: ^5.1.1

  geocoding: ^2.2.0
  cupertino_icons: ^1.0.8

  flutter_naver_map: ^1.4.1+1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/env.json
